[package]
name = "encryptionProject"
version = "0.1.0"
authors = ["N <N@NICK-PC>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
rand = "0.6.5"